apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kots.io/app-slug: ethan-kots
  labels:
    kots.io/app-slug: ethan-kots
    kots.io/backup: velero
  name: test
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJwcm94eS5zdGFnaW5nLnJlcGxpY2F0ZWQuY29tIjp7ImF1dGgiOiJXbU5sVEd0eVpEQjVUVGxVYzNBemFGbFpTbmhwZDFvMUxXaHdSbEJHYkRNNldtTmxUR3R5WkRCNVRUbFVjM0F6YUZsWlNuaHBkMW8xTFdod1JsQkdiRE09In0sInJlZ2lzdHJ5LnN0YWdpbmcucmVwbGljYXRlZC5jb20iOnsiYXV0aCI6IldtTmxUR3R5WkRCNVRUbFVjM0F6YUZsWlNuaHBkMW8xTFdod1JsQkdiRE02V21ObFRHdHlaREI1VFRsVWMzQXphRmxaU25ocGQxbzFMV2h3UmxCR2JETT0ifX19
kind: Secret
metadata:
  annotations:
    kots.io/app-slug: ethan-kots
  creationTimestamp: null
  labels:
    kots.io/app-slug: ethan-kots
    kots.io/backup: velero
  name: kotsadm-replicated-registry
  namespace: default
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kots.io/app-slug: ethan-kots
  labels:
    app: nginx
    kots.io/app-slug: ethan-kots
    kots.io/backup: velero
  name: nginx-test
  namespace: test
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kots.io/app-slug: ethan-kots
  labels:
    app: nginx
    kots.io/app-slug: ethan-kots
    kots.io/backup: velero
  name: nginx
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kots.io/app-slug: ethan-kots
  labels:
    kots.io/app-slug: ethan-kots
    kots.io/backup: velero
  name: nginx-service-test
spec:
  externalName: nginx-test.test.svc.cluster.local
  ports:
  - port: 80
  type: ExternalName
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kots.io/app-slug: ethan-kots
  labels:
    app: nginx
    kots.io/app-slug: ethan-kots
    kots.io/backup: velero
  name: nginx-test
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations:
        kots.io/app-slug: ethan-kots
      labels:
        app: nginx
        kots.io/app-slug: ethan-kots
        kots.io/backup: velero
    spec:
      containers:
      - image: nginxdemos/hello:latest
        name: nginx
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kots.io/app-slug: ethan-kots
  labels:
    app: nginx
    kots.io/app-slug: ethan-kots
    kots.io/backup: velero
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations:
        kots.io/app-slug: ethan-kots
      labels:
        app: nginx
        kots.io/app-slug: ethan-kots
        kots.io/backup: velero
    spec:
      containers:
      - image: proxy.staging.replicated.com/proxy/ethan-kots/ethanreg.azurecr.io/nginxdemos/hello:latest
        name: nginx
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: kotsadm-replicated-registry
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    blah: blahqew
    kots.io/app-slug: ethan-kots
    kots.io/exclude: "false"
    kots.io/placeholder: "true"
    kubernetes.io/ingress.allow-http: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  labels:
    app: nginx
    kots.io/app-slug: ethan-kots
    kots.io/backup: velero
  name: nginx
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
        path: /
      - backend:
          serviceName: nginx-service-test
          servicePort: 80
        path: /test/
  tls:
  - hosts:
    - example.com
    secretName: kotsadm-tls
